### ISSUE TITLE
module 'mxnet.symbol' has no attribute 'broadcast_like'

### ISSUE THREAD

**Issue by wait1988** [RogerChern/mxnext#11]
from .simple import *
  File "/home/SimpleDet/simpledet/mxnext/simple.py", line 323, in <module>
    broadcast_like = mx.sym.broadcast_like
AttributeError: module 'mxnet.symbol' has no attribute 'broadcast_like'

What steps did I miss?

**Comment by lisabug** [comment]
MXNet before version 1.3.1 could cause this problem.
Try to update your MXNet.

**Comment by wait1988** [comment]
@lisabug after I  setup mxnex,the mxnet version changes from 1.3.1 to 1.2.1

**Comment by wait1988** [comment]
@lisabug Yes,you're right.
